#
# Copyright (c) 2022 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
[package]
name = "zenoh-backend-s3"
version = "0.7.0-rc"
repository = "https://github.com/eclipse-zenoh/zenoh-backend-s3"
homepage = "http://zenoh.io"
authors = [
    "kydos <angelo@icorsaro.net>",
    "Julien Enoch <julien@enoch.fr>",
    "Olivier Hécart <olivier.hecart@zettascale.tech>",
    "Luca Cominardi <luca.cominardi@zettascale.tech>",
    "Darius Maitia <darius@zettascale.tech>",
]
edition = "2018"
license = " EPL-2.0 OR Apache-2.0"
categories = ["network-programming", "database"]
description = "Backend for Zenoh using AWS S3 API"

[lib]
name = "zbackend_s3"
crate-type = ["cdylib", "rlib"]

[dependencies]
async-rustls = "0.3.0"
async-std = { version = "=1.12.0", default-features = false, features = ["unstable", "tokio1"] }
async-trait = "0.1.60"
aws-config = "0.51.0"
aws-sdk-s3 = "0.21.0"
aws-smithy-client = "0.51.0"
base64 = "0.21.0"
env_logger = "0.10.0"
futures = "0.3.25"
git-version = "0.3.5"
http = "0.2.8"
hyper = "0.14.23"
hyper-rustls = "0.23.1"
lazy_static = "1.4.0"
log = "0.4.17"
rustls-pemfile = "1.0.1"
serde = "1.0.152"
serde_json = "1.0.89"
tokio = { version = "1.23.1", features = ["full"] }
uhlc = "0.5.2"
zenoh = { git = "https://github.com/sreeja/zenoh", branch = "storage-refactor", features = ["unstable"] }
zenoh_backend_traits = { git = "https://github.com/sreeja/zenoh", branch = "storage-refactor" }
zenoh-buffers = { git = "https://github.com/sreeja/zenoh", branch = "storage-refactor" }
zenoh-codec = { git = "https://github.com/sreeja/zenoh", branch = "storage-refactor" }
zenoh-collections = { git = "https://github.com/sreeja/zenoh", branch = "storage-refactor" }
zenoh-core = { git = "https://github.com/sreeja/zenoh", branch = "storage-refactor" }
zenoh-protocol = { git = "https://github.com/sreeja/zenoh", branch = "storage-refactor" }
zenoh-util = { git = "https://github.com/sreeja/zenoh", branch = "storage-refactor" }
zenoh-keyexpr = { git = "https://github.com/sreeja/zenoh", branch = "storage-refactor" }

[build-dependencies]
rustc_version = "0.4.0"

[package.metadata.deb]
name = "zenoh-backend-s3"
maintainer = "zenoh-dev@eclipse.org"
copyright = "2022 ZettaScale Technology"
section = "net"
license-file = ["LICENSE", "0"]
depends = "zenoh-plugin-storage-manager (=0.7.0-rc)"
